In [1]:
import panda_py
import numpy as np
import math

In [2]:
hostname = '192.168.1.131'
panda = panda_py.Panda(hostname)

print(panda.get_position())
print(panda.get_orientation())
print(panda.get_orientation(True))


[3.06824779e-01 2.75706757e-04 5.90551758e-01]
[ 9.24298694e-01 -3.81669855e-01 -2.04603454e-04  5.80732685e-05]
[ 5.80732685e-05  9.24298694e-01 -3.81669855e-01 -2.04603454e-04]


In [3]:
panda.move_to_start()
pose = panda.get_pose()
print(pose)
pose[2,3] -= .1
q = panda_py.ik(pose)
panda.move_to_joint_position(q)
pose = panda.get_pose()
print(pose)

[[ 7.08451451e-01 -7.05759479e-01 -3.15931012e-04  3.06836144e-01]
 [-7.05759481e-01 -7.08451509e-01  1.23476293e-04  1.86330246e-04]
 [-3.10966366e-04  1.35494348e-04 -9.99999942e-01  5.90561962e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 2.76002769e-03 -9.99993292e-01 -2.40779594e-03  3.07175980e-01]
 [-9.99996149e-01 -2.75932062e-03 -2.96932224e-04 -1.06479062e-03]
 [ 2.90286352e-04  2.40860621e-03 -9.99997057e-01  5.93319983e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [130]:
lower_limits = panda_py.constants.JOINT_LIMITS_LOWER
upper_limits = panda_py.constants.JOINT_LIMITS_UPPER
start_pos = panda_py.constants.JOINT_POSITION_START

# move_to_start actually targets this joint positions not panda_py.constants.JOINT_POSITION_START
start_pos = np.array([ 0. , -0.78539816, 0. , -2.35619449, 0. , 1.57079633, 0.78539816])

print(lower_limits)
print(upper_limits)
print(start_pos)
start_pos.shape
#start_pos[6] = math.pi/4
panda.move_to_joint_position(start_pos)

panda.move_to_start()
pos = panda.get_pose()
#pos[0,3] = 0.4
#panda.move_to_pose(pos)
#pos[1,3] = 0
#pos[2,3] = 0.1
#q = panda_py.ik(pose)
#panda.move_to_joint_position(q)
#print(q)


[-2.8973 -1.7628 -2.8973 -3.0718 -2.8973 -0.0175 -2.8973]
[ 2.8973  1.7628  2.8973 -0.0698  2.8973  3.7525  2.8973]
[ 0.         -0.78539816  0.         -2.35619449  0.          1.57079633
  0.78539816]


In [102]:
pose[0,3] -= .1
print(pose)
q = panda_py.ik(pose)
print(q)

[[ 7.08573167e-01 -7.05634291e-01 -2.07712828e-03  2.07014338e-01]
 [-7.05635580e-01 -7.08574911e-01  1.52314093e-04  2.24030478e-04]
 [-1.57927904e-03  1.35776994e-03 -9.99997831e-01  5.89863640e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[-1.13965067 -1.14105694  0.35440274 -2.10617044  0.37691447  1.02150701
  0.78539816]


In [103]:
panda.move_to_joint_position(q)
pose = panda.get_pose()
print(pose)

[[ 4.22824757e-03 -9.99983747e-01 -3.82464785e-03  2.07901902e-01]
 [-9.99990819e-01 -4.22555762e-03 -7.11127257e-04 -6.58942587e-04]
 [ 6.94954429e-04  3.82761956e-03 -9.99992433e-01  6.92970710e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [98]:
delta = 0.1

for j in range(3):
    panda.move_to_start()
    pose = panda.get_pose()
    for i in range(4):
        pose[j,3] -= delta
        q = panda_py.ik(pose)
        # if any element of q is nan, then the ik failed
        if any([True for x in q if x != x]):
            print(q)
            print('IK failed')
            break
        panda.move_to_joint_position(q)
        p = panda.get_pose()
        print(p)
        pose[j,3] += delta
        q = panda_py.ik(pose)
        if any([True for x in q if x != x]):
            print(q)
            print('IK failed')
            break
        panda.move_to_joint_position(q)
        p = panda.get_pose()
        print(p)
        #print(panda.get_position())
        #print(panda.get_orientation())
    #print(panda.get_orientation(True))
panda.move_to_start() 



[[ 7.54485714e-03 -9.99962818e-01 -4.17575940e-03  2.07862276e-01]
 [-9.99971338e-01 -7.54215601e-03 -6.62230545e-04 -4.60601386e-04]
 [ 6.30711693e-04  4.18063615e-03 -9.99991062e-01  6.92958802e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 6.99962804e-03 -9.99956541e-01 -6.15796865e-03  3.07281922e-01]
 [-9.99975234e-01 -7.00400091e-03  6.88837408e-04  5.61316233e-04]
 [-7.31937890e-04  6.15299454e-03 -9.99980802e-01  6.92625281e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 8.10553506e-03 -9.99966862e-01 -7.58996040e-04  2.07968927e-01]
 [-9.99967000e-01 -8.10594662e-03  5.40745270e-04 -1.88362048e-05]
 [-5.46879732e-04  7.54587964e-04 -9.99999566e-01  6.93507419e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 6.69508010e-03 -9.99959510e-01 -6.01276383e-03  3.07245825e-01]
 [-9.99977204e-01 -6.70022685e-03  8.36235288e-04  3.79042471e-04]
 [-8.76488311e-04  6.00702810e-03 -9.99981574e-01  6.926636

True

In [30]:
for i in range(10):
    pose[2,3] += delta_z
    q = panda_py.ik(pose)
    panda.move_to_joint_position(q)